### ISSUE TITLE
Looking forward with some examples

### ISSUE THREAD

**Issue by sujit-baniya** [s8sg/goflow#19]
Can you please add some examples for using this library?

Also how would I return value of final result from dag?

**Comment by sujit-baniya** [comment]
And Conditional Branch implementation is giving error

```go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x111306c]

goroutine 44 [running]:
github.com/sujit-baniya/goflow/core/sdk/executor.(*FlowExecutor).handleDynamicEnd(0xc0002d1c78, 0xc000303380, {0xc0002ac5c0, 0x33, 0x16})
        /Users/sujit/Sites/labs/go/goflow/core/sdk/executor/executor.go:737 +0xa6c
github.com/sujit-baniya/goflow/core/sdk/executor.(*FlowExecutor).Execute(0xc0002d1c78, 0xc0002d1c58)
        /Users/sujit/Sites/labs/go/goflow/core/sdk/executor/executor.go:1273 +0xc7b
github.com/sujit-baniya/goflow/core/runtime/controller/handler.PartialExecuteFlowHandler(0xc0002d1dd0, 0xc000303320, {0x1433f58, 0xc00032f930})
        /Users/sujit/Sites/labs/go/goflow/core/runtime/controller/handler/partial_execute_flow_handler.go:25 +0xe7

```

**Comment by s8sg** [comment]
@sujit-baniya Thanks for raising this, I'll take a look

**Comment by s8sg** [comment]
Examples are defined [here](https://github.com/s8sg/goflow/tree/master/samples)
